apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  targetNamespace: kgateway-system
  interval: 10m
  chart:
    spec:
      chart: kgateway-crds
      version: "v2.0.5"
      sourceRef:
        kind: HelmRepository
        name: kgateway
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
