apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: flux-system
spec:
  targetNamespace: kgateway-system
  interval: 10m
  dependsOn:
    - name: kgateway-crds
      namespace: flux-system
  chart:
    spec:
      chart: kgateway
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: kgateway
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    controller:
      logLevel: info
      replicas: 1
