apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 0-flux
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: vdk-flux
  path: ./modules/flux
  prune: true
  wait: true
  timeout: 5m0s
