apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - archetypical.software.vega
  resources:
  - atlass
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - secrets
  - configmaps
  - namespaces
  - services
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - archetypical.software.vega
  resources:
  - atlass/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - update
  - patch