apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsVENDQVR1Z0F3SUJBZ0lJUEM2Unp3VVpjRjB3Q2dZSUtvWkl6ajBFQXdRd1BqRVRNQkVHQTFVRUJ4TUsKUzNWaVpYSnVaWFJsY3pFTU1Bb0dBMVVFQmhNRFJFVldNUmt3RndZRFZRUURFeEJQY0dWeVlYUnZjaUJTYjI5MApJRU5CTUI0WERUSTFNREl4TmpBd01EQXdNRm9YRFRNd01ESXhOakF3TURBd01Gb3dQakVUTUJFR0ExVUVCeE1LClMzVmlaWEp1WlhSbGN6RU1NQW9HQTFVRUJoTURSRVZXTVJrd0Z3WURWUVFERXhCUGNHVnlZWFJ2Y2lCU2IyOTAKSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRW5teVBkeTU4Uk9JT3B5N1pkZEtCdXBuQgp0NU1ERVBwN0JyRzN3R2FUVmtxeVhHejBtY280aGxMSzBQMCtDTGVweUlUbmVKaG9kY1JmSThkV1daUUhoNk1qCk1DRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVNZd0NnWUlLb1pJemowRUF3UUQKU0FBd1JRSWhBSUxaWnAraTlDaTNHMTE4QkdySnhsZ2dnSDlac1htbWVldmRJWFNHNWlkOEFpQWdESW40NWZ1QQpmay9aYXB1VFl5ZlVxYjRJekdEZmVwVEcvVXI2M3RyOXh3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: operator
      path: /validate/atlas
  matchPolicy: Exact
  name: validate.atlas.archetypical.software.vega.v1beta1
  rules:
  - apiGroups:
    - archetypical.software.vega
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - atlass
  sideEffects: None