apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: "v1.9.2"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    crds:
      enabled: true
...
