apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentel-operator
  namespace: flux-system
spec:
  targetNamespace: opentel
  interval: 10m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: opentel
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-k8s
    admissionWebhooks:
      certManager:
        enabled: true
      autoGenerateCert:
        enabled: false
