---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    toolkit.fluxcd.io/tenant: vdk-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  install:
    remediation:
      retries: -1
  upgrade:
    force: true
    remediation:
      retries: -1
  values:
    admissionWebhooks:
      enabled: false
    defaultBackend:
      enabled: true
      # image:
      #   repository: "dvdblk/custom-default-backend" # Change this to our own forked image with css
      #   tag: "latest"
      #   pullPolicy: "Always"
      # port: 8080
    extraArgs:
      default-ssl-certificate: "vega/dev-tls"
    controller:
      allowSnippetAnnotations: true
      config:
        annotations-risk-level: Critical
      service:
        type: "ClusterIP"
      hostPort:
        enabled: true
        ports:
          http: 30080
          https: 30443
      nodeSelector:
        ingress-ready: "true"
      tolerations:
      - effect: "NoSchedule"
        key: "node-role.kubernetes.io/master"
        operator: "Equal"
      - effect: "NoSchedule"
        key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
    updateStrategy:
      type: Recreate
