apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kgateway
spec:
  controllerName: kgateway.dev/kgateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vega-gateway
  namespace: vega-system
  labels:
    gateway: vega
spec:
  gatewayClassName: kgateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.local.vega.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: dev-tls
            namespace: vega-system
      allowedRoutes:
        namespaces:
          from: All
    - name: https-wildcard
      protocol: HTTPS
      port: 443
      hostname: "localhost"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: dev-tls
            namespace: vega-system
      allowedRoutes:
        namespaces:
          from: All
  infrastructure:
    parametersRef:
      group: gateway.kgateway.dev
      kind: GatewayParameters
      name: vega-gateway-params
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: vega-gateway-params
  namespace: vega-system
spec:
  kube:
    deployment:
      replicas: 1
    service:
      type: ClusterIP
    podTemplate:
      extraLabels:
        gateway: vega
      nodeSelector:
        ingress-ready: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
    envoyContainer:
      extraVolumeMounts:
        - name: hostport-http
          mountPath: /dev/null-http
        - name: hostport-https
          mountPath: /dev/null-https
    extraVolumes:
      - name: hostport-http
        hostPath:
          path: /dev/null
          type: CharDevice
      - name: hostport-https
        hostPath:
          path: /dev/null
          type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: vega-gateway-hostport
  namespace: vega-system
spec:
  type: ClusterIP
  selector:
    gateway: vega
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vega-gateway-hostport-proxy
  namespace: vega-system
spec:
  selector:
    matchLabels:
      app: vega-gateway-hostport-proxy
  template:
    metadata:
      labels:
        app: vega-gateway-hostport-proxy
    spec:
      nodeSelector:
        ingress-ready: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: proxy
          image: envoyproxy/envoy:v1.32-latest
          ports:
            - containerPort: 30080
              hostPort: 30080
              protocol: TCP
            - containerPort: 30443
              hostPort: 30443
              protocol: TCP
          command:
            - envoy
            - -c
            - /etc/envoy/envoy.yaml
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: envoy-config
          configMap:
            name: vega-gateway-hostport-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vega-gateway-hostport-config
  namespace: vega-system
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: http_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 30080
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: http_passthrough
                    cluster: gateway_http
        - name: https_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 30443
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: https_passthrough
                    cluster: gateway_https
      clusters:
        - name: gateway_http
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: gateway_http
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: gloo-proxy-vega-gateway.vega-system.svc.cluster.local
                          port_value: 8080
        - name: gateway_https
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: gateway_https
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: gloo-proxy-vega-gateway.vega-system.svc.cluster.local
                          port_value: 8443
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901
