apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kgateway
spec:
  controllerName: kgateway.dev/kgateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vega-gateway
  namespace: vega-system
  labels:
    gateway: vega
spec:
  gatewayClassName: kgateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 30443
      hostname: "*.local.vega.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: dev-tls
            namespace: vega-system
      allowedRoutes:
        namespaces:
          from: All
    - name: https-localhost
      protocol: HTTPS
      port: 30443
      hostname: "localhost"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: dev-tls
            namespace: vega-system
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 30080
      allowedRoutes:
        namespaces:
          from: All
  infrastructure:
    parametersRef:
      group: gateway.kgateway.dev
      kind: GatewayParameters
      name: vega-gateway-params
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: vega-gateway-params
  namespace: vega-system
spec:
  kube:
    deployment:
      replicas: 1
    service:
      type: NodePort
      ports:
        - port: 30443
          nodePort: 30443
        - port: 30080
          nodePort: 30080
    podTemplate:
      extraLabels:
        gateway: vega
      nodeSelector:
        ingress-ready: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
