apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uiworkflows.archetypical.software.vega
spec:
  group: archetypical.software.vega
  names:
    kind: UIWorkflow
    listKind: UIWorkflowList
    plural: uiworkflows
    singular: uiworkflow
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties: {}
            type: object
          spec:
            properties:
              name:
                type: string
              version:
                type: string
              description:
                type: string
              steps:
                items:
                  properties: {}
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}