apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsVENDQVR1Z0F3SUJBZ0lJU3RrLzFFT2lQYXd3Q2dZSUtvWkl6ajBFQXdRd1BqRVRNQkVHQTFVRUJ4TUsKUzNWaVpYSnVaWFJsY3pFTU1Bb0dBMVVFQmhNRFJFVldNUmt3RndZRFZRUURFeEJQY0dWeVlYUnZjaUJTYjI5MApJRU5CTUI0WERUSTFNREl5TWpBd01EQXdNRm9YRFRNd01ESXlNakF3TURBd01Gb3dQakVUTUJFR0ExVUVCeE1LClMzVmlaWEp1WlhSbGN6RU1NQW9HQTFVRUJoTURSRVZXTVJrd0Z3WURWUVFERXhCUGNHVnlZWFJ2Y2lCU2IyOTAKSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVIzM3l5Q25OVDdibGNEcEl4RUdwUjVoOAoyZHhoUExvOTBXYm1GOUtHeTR1a0hQaXJ1RDl2amNiZzRzV2hBYTJTQ2F2QnFLMkNYNFpLNEViNm5pb2UvcU1qCk1DRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVNZd0NnWUlLb1pJemowRUF3UUQKU0FBd1JRSWhBUG5wK2N2ZnpSWHlQL25TN2lQQWN4emUxMGVwcFd4dEdMMSsyb2Z0SDA4NkFpQnJzbHNPTlcxZgpMcGs5cFFDWE1YZFo4Q1dLaE1QM1MwK09PakNIR3A1SFdBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: operator
      path: /validate/atlas
  matchPolicy: Exact
  name: validate.atlas.archetypical.software.vega.v1beta1
  rules:
  - apiGroups:
    - archetypical.software.vega
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - atlass
  sideEffects: None